### ISSUE TITLE
The gradlew on eclipse is not working...

### ISSUE THREAD

**Issue by Dalcann** [CJMinecraft01/ForgeModBuilder#10]
http://pastebin.com/raw.php?i=/uLRWzsA4

(also when I tried manually doing it through command prompt it came up  with this: 
"The system cannot find the path specified.
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain")

**Comment by CJMinecraft01** [comment]
That is suggesting that gradle is not installed correctly, I believe. In your user area, you should find a .gradle folder. Try deleting that and then running the command again, it should re-install gradle. (Make sure to do a backup of the folder first just in case)

**Comment by Dalcann** [comment]
I don't have a .gradle in my user folder, and the command doesn't install it. I tried installing gradle but I can't figure out how to. (I tried using homebrew and scoop.) so... any ideas? (don't feel pressured to respond, if trying to get me through this is too much trouble then it's completely fine.)

**Comment by CJMinecraft01** [comment]
Are you running gradle or gradlew?

**Comment by Dalcann** [comment]
so I figure out how to install gradle. I wasn't using the powershell while I was using the command. I actually didn't even know that you had to run a command to use the powershell. Also, I needed to use gradle, not gradlew. I'm new to this so I didn't quite understand everything, but thanks for helping.

**Comment by Dalcann** [comment]
I figured out that you needed to enter a command to use powershell. this allowed me to install gradle using scoop. I also figured out that I needed to use gradle not gradlew for setting up the workspace and other commands. Thank you for helping me with this. I'm fairly new to this, and before now I didn't even know what gradle was. Now I have a slightly better understanding. thanks for the help.
