### ISSUE TITLE
Not Making New Project

### ISSUE THREAD

**Issue by Jjcobb03** [CJMinecraft01/ForgeModBuilder#12]
Whenever I try to make a new project, it starts working, then gets an error saying unhandled exception has occurred in your application... It also says that an attempt was made to move the file pointer before the beginning of the file... please help

extra stuff from the error message
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ForgeModBuilder-0.1.1.0
    Assembly Version: 0.1.1.0
    Win32 Version: n/a
    CodeBase: file:///C:/Users/jacob/Desktop/ForgeModBuilder-0.1.1.0.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by CJMinecraft01** [comment]
So what was FMB doing before this error occurred. Did it download the file? Also, in the area where you selected the project to be installed, is there a file called temp.zip or something like that?

**Comment by CJMinecraft01** [comment]
So I've looked into what causes this error, and apparently it's due to the downloaded file being corrupt like you said. Try downloading the file from forge and see if that is corrupt

**Comment by Haveachin** [comment]
So I downloaded the repository and compile it myself... and it works.
I don't know why it works now but I think it has something to do with the WebClient.

![capture](https://user-images.githubusercontent.com/30272106/38759167-bc6e5244-3f74-11e8-86cb-10c9354d790b.PNG)

**Comment by CJMinecraft01** [comment]
Really strange. I'm going to have to see what the cause of this is because I've never seen it before.

**Comment by JohnTheLate** [comment]
I am having the same issue now. When I tried to create a project 2 months ago, it worked perfectly fine. Now, I am getting an error. Glad to see you're working on it!

**Comment by CJMinecraft01** [comment]
So I've looked into this and I don't belive it is an error my side. If it is, obviously I'll fix it, but I was looking online and found a possible fix.

Reference: https://github.com/PeterTh/gedosato/issues/233

I'm not sure if it is relevant but if it then that's great!

**Comment by BeesPlease** [comment]
getting the same bug here, unable to create a new project.

**Comment by CJMinecraft01** [comment]
It's highly likely that something has changed on the forge website to cause this but I am uncertain. Doesn't it do the same on the previous version?

**Comment by 4kills** [comment]
I have the same bug now as well, please fix this as soon as possible! @CJMinecraft01

**Comment by acoolghuy** [comment]
The error must be the way you are getting the forge file because i get the same error as everyone else not being able to start a new project.
If i click continue on the error box and then click on the link for the forge file and download it then extract it to a folder everything works fine from that point.

**Comment by CJMinecraft01** [comment]
This is a really strange error as this has worked for over 6 months and then 2 months ago it breaks. I'm going to look into this and try and sort it out. I'm entering exam season so my time is limited so I hope to try and sort it as soon as I can

**Comment by CJMinecraft01** [comment]
So I'm currently tracking down the issue and I've noticed something strange which never used to happen. When downloading the zip file, it actually downloads a blank file, hence it can't unzip it as the downloaded file is already corrupted before FMB has touched it. I'm going to keep you all updated to let you know how this is going along

**Comment by CJMinecraft01** [comment]
Ok, so I've found the issue. Forge must have updated their website security protocol to something which wasn't my current one (it is TLS 1.2) so I needed to ensure that they were the same version so they would cooperate correctly. This will now be updated in the latest version I will hopefully release ASAP
