### ISSUE TITLE
Building ForgeModBuilder

### ISSUE THREAD

**Issue by MinerCraftGuy** [CJMinecraft01/ForgeModBuilder#13]
It seems you haven't included the SLN file for people to be able to build the solution themselves.

Please see if you're able to put that into your repository as well

**Comment by CJMinecraft01** [comment]
I already have the SLN file for download on another issue. The way the project is currently set up, I can't easily add the SLN file to it but hopefully, when I complete my rewrite over the summer, you will be able to see it. In the meanwhile, here it is: https://github.com/CJMinecraft01/ForgeModBuilder/issues/9
