### ISSUE TITLE
Check for updated MCP: snapshot

### ISSUE THREAD

**Issue by MinerCraftGuy** [CJMinecraft01/ForgeModBuilder#14]
At the moment you're always using the MCP: snapshot_20171003

Can you please check if you are able to update that when creating a new project to the latest MCP: snapshot as well.

You already have the code to get the latest in your source

**Comment by CJMinecraft01** [comment]
When downloading a project, FMB does not automatically try and update the MCP, it is an optional thing you can do afterwards. The reason why the MCP remains on snapshot_20171003 as that is the most recent stable version, hence forge always uses it in the downloads of a new project. To get round this, press no to setup once the project has downloaded and then press update forge version, like you normally would. In the future I might add a feature where you can optionally auto update upon download, however this is not currently implemented, sorry.
