### ISSUE TITLE
FAILED

### ISSUE THREAD

**Issue by pixadventurer** [CJMinecraft01/ForgeModBuilder#15]
:fixMcSources
:applySourcePatches
:remapMcSources
:recompileMc FAILED

BUILD FAILED

**Comment by CJMinecraft01** [comment]
Is that the whole console log? If so you might need to provide more context. At the moment, FMB isn't very great at logging errors from gradle so try running gradle with the command and see what error comes up

**Comment by CJMinecraft01** [comment]
Closed for inactivity
