### ISSUE TITLE
MacOS and Linux compatibility

### ISSUE THREAD

**Issue by simonmeusel** [CJMinecraft01/ForgeModBuilder#2]
How can I use this program on MacOS or Linux?

**Comment by CJMinecraft01** [comment]
I'm not too sure, I doubt it as it is an exe file, but there might be a converter to a file in which mac or Linux could understand

**Comment by simonmeusel** [comment]
Could you provide some information on how you build the mod from source? That is probably somehow repeatable for mac and linux

**Comment by CJMinecraft01** [comment]
What do you mean by source?

**Comment by CJMinecraft01** [comment]
If you want to just build and setup a mod, just run the correct gradle commands. Make sure to open the command window in the area where your mod is located (i.e. use cd)
For building use: gradlew build
For setup use: gradlew setupDecompWorkspace
For eclipse use: gradlew eclipse
For idea use: gradlew idea
and gradlew genIntellijRuns
For refreshing an environment use: gradlew setupDecompWorkspace --refresh-dependencies

**Comment by simonmeusel** [comment]
I know how to create a mod.
But how do you compile this program? How do you get a exe from all the cs files?

**Comment by CJMinecraft01** [comment]
Oh, well the problem is, is that I don't know the languages that each platform supports. The cs files are purely the mainframe which works for Windows but I'm not sure about the other platforms
