### ISSUE TITLE
Cant Setp a Projekt

### ISSUE THREAD

**Issue by asdanjer** [CJMinecraft01/ForgeModBuilder#21]
I get the following outputs when creating a new projekt:
"please choose a valid forge project"
"Whoud you like to set up now?"
"Please open a projekt?"
If I try to open it afterwards it does not work.
Anything else does nothing.
The Console is not really an help either.
https://pastebin.com/hZMK3G8x

**Comment by lopez1de** [comment]
I have the same problem.

**Comment by FootrottFlats** [comment]
Same problem... scrapping Forge Mod Loader.  Doesnt work.

**Comment by CJMinecraft01** [comment]
The Forge Mod Builder has not yet been updated to 1.13. In 1.13 the setup command has changed and at the moment, the commands are hard coded. I do plan to change this when I get round to finishing an update I've been working on over a long period of time. I am also aware of a ton of issues that people have had with the most recent versions and aim to get back to development on this project as soon as possible. Thanks for letting me know though. (Also, the console in FMB does not provide any error logs which is a massive limitation of the current code)

**Comment by CJMinecraft01** [comment]
This should now be fixed in the latest version thanks to Dogatron03
