### ISSUE TITLE
Invalid Uri

### ISSUE THREAD

**Issue by mrdacom** [CJMinecraft01/ForgeModBuilder#22]
Error:
Found download link: forge-1.13.2-25.0.214-mdk.zip
An error occurred:
Ungültiger URI: Das URI-Format konnte nicht bestimmt werden.
Translated: 
Invalid URI: The URI format could not be determined.

**Comment by eehunter** [comment]
Same problem here

**Comment by ZachT112** [comment]
Is this just the latest version, and is there an archived version of the software you can download?

**Comment by Jiraiyah** [comment]
may i suggest something? how about giving us an option to use a local zip for forge mdk? this way if something happens and the link won't work we can use a local instance ? also an ability to set min and max memory usage would be nice, i have 32 gigabytes of memory and i can easily set 12 gig for deobfuscation, cuts the time there a lot for me.

**Comment by ravenxxx5** [comment]
I have the same problem

**Comment by eehunter** [comment]
If I had to guess, forge changed their website again, meaning that FMB will have to be updated.

**Comment by CJMinecraft01** [comment]
This should now be fixed in the latest version thanks to Dogatron03
