### ISSUE TITLE
1.12.2 Support?

### ISSUE THREAD

**Issue by burlingk** [CJMinecraft01/ForgeModBuilder#3]
When running the program, it does not give me the option to use version 1.12.2, even though it has been available for quite some time.

Most of the mods I am using (and thus, want to maintain compatibility with in my own work) have already moved on to 1.12.2 with no desire on the part of the maintainers to look back.

**Comment by CJMinecraft01** [comment]
What function are you using, are you trying to create a new project or update a current one?

**Comment by Sparkyx-Sparks** [comment]
Hi, I get the same problem, 1.12.2 isn't showing anywhere. I needed to install version 0.1.0.7 to get it. If I can help that would be great! By the way, I was using the function "New Project".

**Comment by burlingk** [comment]
Both.

I am using the 0.1.0.8 version. I initially installed the 0.1.0.7, but let it update on the first run.

**Comment by CJMinecraft01** [comment]
Strange, I have just ran this and it works entirely. I recommend going to options and clear version cache and then do help and sync versions

**Comment by CJMinecraft01** [comment]
Ok, I have managed to recreate the bug, it only happens when you have an empty version cache. I'll look for a fix

**Comment by CJMinecraft01** [comment]
I have found the fix. For now, go to %AppData%\ForgeModBuilder\versions.json and replace it with the following:
https://pastebin.com/mgtPJRWV
