### ISSUE TITLE
Don't include the latest Forge 

### ISSUE THREAD

**Issue by PlazmosPhoenix** [CJMinecraft01/ForgeModBuilder#7]
_FMB 0.1.1.0 only works with Forge up to version 1.12.1, could it also include 1.12.2?_

**Comment by CJMinecraft01** [comment]
What version of Forge Mod Builder are you using? I have a versions file on one of the other issues which should fix this issue. If this is due to the latest version, I will be sure to fix it

**Comment by PlazmosPhoenix** [comment]
Oh ok, sorry about, I forgot their was closed issues area, my bad.... sorry
