### ISSUE TITLE
Lack of build instructions

### ISSUE THREAD

**Issue by BearzRobotics** [CJMinecraft01/ForgeModBuilder#9]
Could you include build instructions in the readme.

**Comment by CJMinecraft01** [comment]
When you say build instructions, do you mean like using the build.gradle or something else?

**Comment by BearzRobotics** [comment]
I came across your project and would like to compile it on my system. It's just that you didn't provide any instructions on how to do this. I couldn't find a make, cmake, qmake, Vs project file ect.

**Comment by CJMinecraft01** [comment]
The only project file I have is a .sln file if that's what you are looking for

**Comment by BearzRobotics** [comment]
Yes, that is it. That project file will let me easily build the program from the command line.

**Comment by CJMinecraft01** [comment]
I'll just attach it to this then.
[ForgeModBuilder.zip](https://github.com/CJMinecraft01/ForgeModBuilder/files/1628553/ForgeModBuilder.zip)
